[build]
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "react-scripts start"
  functions = "netlify/functions"
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/redditProxy"
  status = 200
  force = true

